services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-gymrat}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gymrat}'
      - 'POSTGRES_USER=${POSTGRES_USER:-gymrat}'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

